project_id = "hhaxlgxzvwvfgevzkmka"

[functions.generate-recipes]
verify_jwt = false

[functions.shopping-suggestions]
verify_jwt = false

[functions.generate-cooking-steps]
verify_jwt = false

[functions.parse-recipe]
verify_jwt = false

[functions.estimate-nutrients]
verify_jwt = false
